### ISSUE TITLE
[Assignment 3] TO-DO

### ISSUE THREAD

**Issue by martinferianc** [martinferianc/Robotics-EIE3#16]
- [ ] README for Exercise 1 - George
- [ ] Exercise 2 coding and also README - Owen & George
- [ ] Check all the exercises for demonstration - Martin & Mike
