### ISSUE TITLE
To-Do:

### ISSUE THREAD

**Issue by martinferianc** [martinferianc/Robotics-EIE3#30]
- [x] Define a method to return a standard deviation of x,y,theta
- [x] Rewrite update state so that it takes an argument the pose of the ultra sound to refine the precision
- [x] Change the inaccuracy of the ultrasound depending on the distance
- [x] Change the navigation_to_waypoint according to the current precision, if not precise enough do further measurements
